"""Created Tables

Revision ID: 06bbd92c9b4f
Revises: 25cb1b89d020
Create Date: 2023-12-11 11:23:08.275580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bbd92c9b4f'
down_revision = '25cb1b89d020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
