""" Initial db creation 

Revision ID: 529b012ef899
Revises: 
Create Date: 2023-12-11 10:09:58.601535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529b012ef899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
